# 4. Game of craps

## Code of the game + explaination (as comments in the code):
```{r, echo=TRUE}
play_craps <- function() {
  # at first a random number between 1 & 6.99 is selected, using the floor-
  # function, an random integer between 1 & 6 is created
  first_throw <- floor(runif(1, min=1, max=6.99))
  # using a if/else if/else-query, it is determined if the number results in an
  # instant win/lose or if the game need to be played further
  if (first_throw == 6) {
    print("WoW a six! You won the game!")
  }
  else if (first_throw == 1) {
    print("Unlucky, a 1! You lose, try again!")
  }
  else {
    cat("Your number is", first_throw, "- try to throw it again within 3 tries!\n")
    # A for-loop is now used to simulate the next throws
    for (i in 1:3) {
      next_throw <- floor(runif(1, min=1, max=6.99))
      cat("Throwing dice... you got a", next_throw, "\n")
      # if the throw is identical to the first one, the game is won & the for-
      # loop is ended
      if (next_throw == first_throw) {
        cat("Nice! You managed to repeat your number on try No.", i, "- You win!")
        break
      }
      # if the throw is not identical to the first one, the game continues
      else if (i != 3) {
        cat("Not quite the same, you have", 3-i, "tries left.\n")
      }
    }
    # if the for loop is broken and the game has not been won, the game is lost &
    # an according message is displayed
    if (next_throw != first_throw) {
      print("Unlucky, you could not repeat your number within 3 throws. You lose, try again!")
    }
  }
}
```

## Using the function with the different possible outcomes:
### a) Getting a 6 and winning instantly:
```{r, echo=FALSE}
set.seed(7)
play_craps()
```
### b) Getting a 1 and losing instantly:
```{r, echo=FALSE}
set.seed(12)
play_craps()
```
### c) Playing the full game and winning:
```{r, echo=FALSE}
set.seed(2)
play_craps()
```
### d) Playing the full game and losing:
```{r, echo=FALSE}
set.seed(1)
play_craps()
```
