---
title: "Case Study 4"
subtitle: "AKSTA Statistical Computing"
author: "Tatzberger Jonas, Rasser Thomas, Grübling Alexander"
date: "22.06.2024"
output: pdf_document
---

# Exercises

```{r import_libraries, message=FALSE, warning=FALSE, include=FALSE, echo=FALSE}

import_library <- function(library_name) {
  if (!requireNamespace(library_name, quietly = TRUE)) {
    install.packages(library_name)
  }
  library(library_name, character.only = TRUE)
}

# --------------------------

import_library("shiny")
import_library("shinydashboard")
import_library("shinyalert")
import_library("DT")

import_library("ggplot2")
import_library("plotly")
import_library("readr")
import_library("dplyr")
import_library("tidyr")
import_library("knitr")

import_library("viridis")
import_library("rlang")    # For sym() and !! 
import_library("rnaturalearth")
import_library("rnaturalearthdata")

import_library("RColorBrewer")
colorblind_palette <- brewer.pal(4, "Set2")

```

```{r}

# Load CIA data and turn it into a tibble
cia_data <- jsonlite::read_json("data/data_cia.json")
cia_data_tibble <- purrr::map_df(cia_data, tibble::as_tibble)

# Rename columns into more legidible names
cia_data_tibble <- cia_data_tibble %>%
  rename(
    "Country" = country,
    "ISO3" = ISO3,
    "Continent" = continent,
    "Subcontinent" = subcontinent,
    "Status" = status,
    "Median_age" = median_age,
    "Youth_unemployment_rate" = youth_unempl_rate,
    "Net_migration_rate" = net_migr_rate,
    "Electricity_from_fossil_fuel" = electricity_fossil_fuel,
    "Area" = area,
    "Population_growth_rate" = pop_growth_rate,
    "Life_expectancy" = life_expectancy,
    "Population" = population,
  )

# Update Continent and Subcontinent for Kosovo
cia_data_tibble <- cia_data_tibble %>%
  mutate(
    Continent = if_else(Country == "Kosovo", "Europe", Continent),
    Subcontinent = if_else(Country == "Kosovo", "Balkan Peninsula", Subcontinent)
  )

# Load natural earth data for countries
world <- ne_countries(scale = "medium", returnclass = "sf")

# Merge your data with the world data
world_data <- world %>%
  left_join(cia_data_tibble, by = c("iso_a3" = "ISO3"))


glimpse(cia_data_tibble)

```

```{r }

# Define UI
# ---------------------------------------------------------------------------
ui <- fluidPage(
  tabsetPanel(
    tabPanel("Univariate analysis",
      sidebarLayout(
        sidebarPanel(
          fluidRow(
            box(
              selectInput("variable", "Select a variable:",
                         choices = c("Median age"                   = "Median_age",
                                     "Youth unemployment rate"      = "Youth_unemployment_rate",
                                     "Net migration rate"           = "Net_migration_rate",
                                     "Population growth rate"       = "Population_growth_rate",
                                     "Electricity from fossil fuel" = "Electricity_from_fossil_fuel",
                                     "Life expectancy"              = "Life_expectancy")),
              actionButton("viewData", "View Raw Data"),
              DTOutput("dataTable")
            )
          ),
        ),
        mainPanel(
          tabsetPanel(
            tabPanel("Map",
               helpText("The map contains values of the selected variables. 
                        The countries with gray areas have a missing value 
                        for the visualized variable."),
               plotlyOutput("worldMap")
            ),
            tabPanel("Boxplot (overall)",
              plotlyOutput("overallBoxplot")
            ),
            tabPanel("Boxplot per continent",
              plotlyOutput("continentBoxplot")
            )
          )
        )
      )
    ),
    tabPanel("Multivariate analysis",
      sidebarLayout(
        sidebarPanel(
          fluidRow(
            box(
              selectInput("variable1", "Select a variable 1:",
                         choices = c("Median age"                   = "Median_age",
                                     "Youth unemployment rate"      = "Youth_unemployment_rate",
                                     "Net migration rate"           = "Net_migration_rate",
                                     "Population growth rate"       = "Population_growth_rate",
                                     "Electricity from fossil fuel" = "Electricity_from_fossil_fuel",
                                     "Life expectancy"              = "Life_expectancy")),
              selectInput("variable2", "Select a variable 2:",
                         choices = c("Median age"                   = "Median_age",
                                     "Youth unemployment rate"      = "Youth_unemployment_rate",
                                     "Net migration rate"           = "Net_migration_rate",
                                     "Population growth rate"       = "Population_growth_rate",
                                     "Electricity from fossil fuel" = "Electricity_from_fossil_fuel",
                                     "Life expectancy"              = "Life_expectancy")),
              selectInput("scaleBy", "Scale points by:",
                          choices = c("Area" = "Area",
                                      "Population" = "Population")),
              DTOutput("dataTable")
            )
          ),
        ),
        mainPanel(
          plotlyOutput("scatterPlot")
        )
      )
    )
  )
)


# Define Server
# ---------------------------------------------------------------------------
server <- function(input, output, session) {
  
  # TODO: uncomment after testing
  # shinyalert(title = "Welcome", 
  #            text = "This app allows you to visualize various plots from the cia database", 
  #            type = "info", 
  #            closeOnClickOutside = TRUE
  # )
  
  # Render the basic data table
  output$dataTable <- renderDT({
    req(input$viewData)
    isolate({
      datatable(cia_data_tibble[, c("Country", "Continent", input$variable)], 
                options = list(pageLength = 15))
    })
  }, server = FALSE)
  
  # Render world map
  output$worldMap <- renderPlotly({
    req(input$variable) # Ensure a variable is selected
    world <- ne_countries(scale = "medium", returnclass = "sf")
    
    # Prepare the column name to include in the aes_string
    variable_name <- sprintf("`%s`", input$variable)
    
    world_data <- left_join(world, cia_data_tibble, by = c("iso_a3" = "ISO3"))
    
    # Create the ggplot object
    p <- ggplot(data = world_data) +
     geom_sf(aes_string(fill = variable_name, 
                        geometry = "geometry",
                        group = 1,
                        text = sprintf("paste(iso_a3, ': ', %s)", variable_name)
                       ), 
             color = "white") +
     scale_fill_viridis_c(option = "viridis", name = input$variable) +
     theme_minimal() +
     theme(legend.position = "bottom")
    
    # Convert to plotly for interactivity
    ggplotly(p, tooltip = c("text"))
  })
  
  # Render Overall Boxplot
  output$overallBoxplot <- renderPlotly({
    req(input$variable)  # Ensure a variable is selected
    
    # Prepare the column name to include in the aes_string
    variable_name <- sprintf("`%s`", input$variable)
  
    # Creating the boxplot using ggplot
    p <- ggplot(cia_data_tibble, aes_string(y = variable_name)) +
      geom_boxplot() +
      labs(y = input$variable) +
      theme_minimal()
    
    # Convert to Plotly for interactivity
    ggplotly(p)
  })
  
  # Render Boxplot per Continent
  output$continentBoxplot <- renderPlotly({
    req(input$variable)  # Ensure a variable is selected
    # Prepare the column name to include in the aes_string
    variable_name <- sprintf("`%s`", input$variable)
  
    # Creating the boxplot using ggplot grouped by continent
    p <- ggplot(cia_data_tibble, aes_string(x = "Continent", y = variable_name, fill = "Continent")) +
      geom_boxplot() +
      labs(y = input$variable) +
      theme_minimal() +
      theme(legend.position = "none")
    
    # Convert to Plotly for interactivity
    ggplotly(p)
  })
  
  # Renderscatterplot of selected variables
  output$scatterPlot <- renderPlotly({
    req(input$variable1, input$variable2, input$scaleBy)  # Ensure that the variables are selected
    
    # Create the scatterplot using ggplot
    p <- ggplot(cia_data_tibble) + aes_string(x=input$variable1, y=input$variable2, color="Continent", size=input$scaleBy, text="Country") + geom_point(alpha=0.7) + ggtitle(paste(input$variable, "vs.", input$variable2, "scaled by", input$scaleBy))
    ggplotly(p, tooltip=c("text", "x", "y", "size"))
  })

}

# Run the application
# ---------------------------------------------------------------------------
shinyApp(ui = ui, server = server)

```

</div>

</pre>
